# Generated by Django 2.2.1 on 2019-05-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isportbook_main', '0006_companyaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sports',
            field=models.ManyToManyField(to='isportbook_main.Sport'),
        ),
    ]
