apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: order-service-db-env-file
            - configMapRef:
                name: order-service-env-file
            - secretRef:
                name: order-service-db-secret-file

