version: '3'
services:
    counter:
        build: pythonapp/Dockerfile-dev
        links:
            - redis
        volumes:
            - ./pythonapp:/app
    frontend:
        build: frontend/Dockerfile-dev
        ports:
            - "8080:80"
        volumes:
            - ./frontend/src:/webapp
        links:
            - counter
    redis:
        image: redis:5-alpine

