version: '3'
services:
    counter:
        image: ykn18/pythoncounter2
        links:
            - redis
    frontend:
        image: ykn18/pythoncounternginx
        ports:
            - "8080:80"
        links:
            - counter
    redis:
        image: redis:5-alpine

