version: '3'
services:
    counter:
        build: ./Dockerfile-dev
        links:
            - redis
        ports:
            - "8080:5000"
        volumes:
            - ./:/app
    redis:
        image: redis:5-alpine

