# Generated by Django 2.2.1 on 2019-05-13 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isportbook_main', '0004_auto_20190513_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='isportbook_main.City'),
            preserve_default=False,
        ),
    ]
