# Generated by Django 2.2.1 on 2019-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isportbook_main', '0008_booking_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='uuid',
            field=models.UUIDField(default=None, editable=False, null=True, unique=True),
        ),
    ]
