# Generated by Django 2.2.1 on 2019-05-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isportbook_main', '0011_auto_20190518_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='icon',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
