# Generated by Django 2.2.1 on 2019-05-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isportbook_main', '0012_sport_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='icon',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
