# Generated by Django 2.2.1 on 2019-05-25 20:15

from django.db import migrations, models
import django.db.models.deletion
import isportbook_main.models.models_utils.integer_range_field


class Migration(migrations.Migration):

    dependencies = [
        ('isportbook_main', '0017_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isportbook_main.Profile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='telephone',
            field=models.CharField(max_length=50, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='isportbook_main.Booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='cleaning',
            field=isportbook_main.models.models_utils.integer_range_field.IntegerRangeField(verbose_name='Cleaning'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='closeness',
            field=isportbook_main.models.models_utils.integer_range_field.IntegerRangeField(verbose_name='Closeness'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='passion',
            field=isportbook_main.models.models_utils.integer_range_field.IntegerRangeField(verbose_name='Passion'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='punctuality',
            field=isportbook_main.models.models_utils.integer_range_field.IntegerRangeField(verbose_name='Punctuality'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='skill',
            field=isportbook_main.models.models_utils.integer_range_field.IntegerRangeField(verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='value_for_money',
            field=isportbook_main.models.models_utils.integer_range_field.IntegerRangeField(verbose_name='Value for money'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=3, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='awards',
            field=models.TextField(blank=True, max_length=500, verbose_name='Awards'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, max_length=500, verbose_name='Certifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isportbook_main.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='open_times',
            field=models.TextField(blank=True, max_length=500, verbose_name='Open times'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='profiles/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Post code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='services',
            field=models.TextField(blank=True, max_length=500, verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='super_powers',
            field=models.TextField(blank=True, max_length=500, verbose_name='Super powers'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='icon',
            field=models.ImageField(null=True, upload_to='sports/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
