apiVersion: v1
kind: Service
metadata:
  name: order-service-db
spec:
  ports:
    - port: 27017
  selector:
    app: order-service-db
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
  - port: 8080
  selector:
    app: order-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-db
spec:
  selector:
      matchLabels:
          app: order-service-db
  template:
    metadata:
      labels:
        app: order-service-db
    spec:
      containers:
      - name: order-service-db
        image: mongo:latest
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: order-service-db-env-file
        - secretRef:
            name: order-service-db-secret-file
        volumeMounts:
            - mountPath: /data/db
              name: order-service-db-volume
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 20
          timeoutSeconds: 1

      volumes:
      - name: order-service-db-volume
        hostPath:
            path: /order-service-db-volume
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
      matchLabels:
          app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service-prod:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: order-service-db-env-file
        - configMapRef:
            name: order-service-env-file
        - secretRef:
            name: order-service-db-secret-file
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3


