apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-pycounter
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/volumes/v000
    type: DirectoryOrCreate
