apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-env-file
data:
  KAFKA_ADDRESS: kafkaa:9092
  KAFKA_GROUP_ID: order-service-group
  KAFKA_MAIN_TOPIC: main-topic
  MONGODB_HOSTNAME: order-service-db
  MONGODB_PORT: "27017"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-db-env-file
  namespace: default
data:
  MONGO_INITDB_DATABASE: admin