# Generated by Django 2.2.1 on 2019-06-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isportbook_main', '0018_auto_20190525_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Certifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='open_times',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Open times'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='services',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Services'),
        ),
    ]
